require:
  - rubocop-performance
  - rubocop-rspec

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/NumericPredicate:
  AutoCorrect: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/BlockLength:
  Exclude: ['**/*.gemspec', 'spec/**/*']

Metrics/ModuleLength:
  Exclude: ['**/*.gemspec', 'spec/**/*']

Layout/LineLength:
  Max: 80

Naming/MethodParameterName:
  AllowedNames: ['io', 'id', 'to', 'by', 'on', 'in', 'at', 'ip', 'db', 'iv']

Naming/VariableNumber:
  EnforcedStyle: snake_case
